export const data = [
{
    imgLink: "workCard1",
    mainText: "Описание",
    mainTextDescription:"Работа на фрилансе верстка по макету",
    secondText: "Направление:",
    secondTextDescription:"FrontEnd-Разработка",
},
{
    imgLink: "workCard2",
    mainText: "Описание",
    mainTextDescription:"Работа на фрилансе верстка по макету",
    secondText: "Направление:",
    secondTextDescription:"FrontEnd-Разработка",
},
{
    imgLink: "workCard3",
    mainText: "Описание",
    mainTextDescription:"Работа на фрилансе верстка по макету",
    secondText: "Направление:",
    secondTextDescription:"FrontEnd-Разработка",
},
{
    imgLink: "workCard4",
    mainText: "Описание",
    mainTextDescription:"Работа на фрилансе верстка по макету",
    secondText: "Направление:",
    secondTextDescription:"FrontEnd-Разработка",
},
{
    imgLink: "workCard5",
    mainText: "Описание",
    mainTextDescription:"Работа на фрилансе верстка по макету",
    secondText: "Направление:",
    secondTextDescription:"FrontEnd-Разработка",
},
{
    imgLink: "workCard6",
    mainText: "Описание",
    mainTextDescription:"Работа на фрилансе верстка по макету",
    secondText: "Направление:",
    secondTextDescription:"FrontEnd-Разработка",
},
{
    imgLink: "workCard7",
    mainText: "Описание",
    mainTextDescription:"Работа на фрилансе верстка по макету",
    secondText: "Направление:",
    secondTextDescription:"FrontEnd-Разработка",
},
{
    imgLink: "workCard8",
    mainText: "Описание",
    mainTextDescription:"Работа на фрилансе верстка по макету",
    secondText: "Направление:",
    secondTextDescription:"FrontEnd-Разработка",
},
{
    imgLink: "workCard9",
    mainText: "Описание",
    mainTextDescription:"Работа на фрилансе верстка по макету",
    secondText: "Направление:",
    secondTextDescription:"FrontEnd-Разработка",
},
]
